# Generated by Django 3.2.9 on 2021-11-20 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='_clients_client_likes_+', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
    ]
